# Nombre del microservicio
spring.application.name=api_rest_mcs_registro

# Puerto del servidor (Importante para que le pegues a localhost:5000 en Postman)
server.port=5000

# URL para conectarnos a la base de datos H2 denominada testdb la cual existe en memoria
spring.datasource.url=jdbc:h2:mem:testregistro
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.sql.init.mode=always


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Muestra en la consola del back las sentencias create e insert que se ejecutan
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer=DEBUG